// Sample data for local development mode (npm run dev).
// In production, real data comes from window.__DATA__ (set by index.php).
export const DEV_DATA = {
  content: {
    brand: 'Uni Sushi',
    heroEyebrow: 'Kuta · Bali',
    heroTagline: 'Great food, great company, every day.',
    heroLede: 'Your neighborhood gathering spot in Kuta — international flavors made with local produce, signature cocktails, comfort food classics, and the best hangover cure in town.',
    heroImage: '/images/hero.jpg',
    logo: "/images/Logo.jpeg",
    aboutEyebrow: 'Our story',
    aboutTitle: 'Your neighborhood favorite since 2016',
    aboutImage: '/images/About01.jpg',
    aboutText: "Founded in 2016, Uni blends international flavors with local produce — a place for sports, late nights and the best hangover cure in town.\n\nWe're more than just a restaurant. We're your neighborhood gathering spot where great food meets great company, and every game feels like a celebration.\n\nFrom our signature cocktails to comfort food classics, everything is crafted with passion and served with the warmth that makes Uni feel like home.",
    address: 'Jl. Benesari, Kuta, Kec. Kuta, Kabupaten Badung, Bali 80361, Indonesia',
    phone: '+62 895-4216-45000',
    whatsapp: '62895421645000',
    email: 'contact@unicafebali.com',
    instagram: 'unicafebali',
    mapsQuery: 'https://maps.app.goo.gl/LE8RhSwv8ccwumtr9',
    hours: [
      { h: 'Open Close 12 am' },
    ],
  },
  categories: [
    { id: 1, name: 'Breakfast, Brunch & Lunch' },
    { id: 2, name: 'Asian All Dining & Main Course' },
    { id: 3, name: 'Burgers & Sandwiches & Hot Dogs' },
    { id: 4, name: 'Pizza & Pasta' },
    { id: 5, name: 'Salads & Soups'},
    { id: 6, name: 'Sides & Snacks' },
    { id: 7, name: 'Desserts & Cakes' },
    { id: 8, name: 'Coffee & Tea' },
    { id: 9, name: 'Beverage' },
    { id: 10, name: 'Mocktails & Fresh Juices' },
    { id: 11, name: 'Cocktails & Spirits' },

  ],
  items: [
    // // Breakfast, Brunch & Lunch
    // { id: 1, category_id: 1, name: 'Full English Brekky', description: 'Eggs, bacon, sausage, hash brown, baked beans, grilled tomato, toast.', tag: '', featured: true, image: '/images/DSC00054.jpg' },
    // { id: 2, category_id: 1, name: 'Egg benny', description: 'Toasted Muffin, Poached Eggs, Baby Spinach, Hollandaise Sauce', tag: '', image: '' },
    // { id: 3, category_id: 1, name: 'Big boy warp', description: 'Homemade Beef Patty, Bacon, Has Brown, Scrambled egg, cheese', image: '' },
    // { id: 4, category_id: 1, name: 'Uni Brekky Burger', description: 'Homemade Beef Patty, Fried Egg, Hash Brown, Cheese, Burger Bun', image: '' },
    // { id: 5, category_id: 1, name: 'Croissant Stacker', description: 'Croissant, Fried Egg, Ham, Cheese, Fresh Tomato, Basil, Avocado Smash', image: '' },
    // { id: 6, category_id: 1, name: 'Croissant Tuna', description: 'croissant, Smashed Boiled Egg, Tuna Mayo', image: '' },
    // // Asian All Dining & Main Course
    // { id: 7, category_id: 2, name: 'Nasi Goreng', description: 'fried rice, Vegetables, Prawn Cracker, Traditional Pickle, Chicken Satay', image: '/images/DSC00107.jpg' },
    // { id: 8, category_id: 2, name: 'Mie Goreng', description: 'fried noodle, vegetables, sunny side egg, prawn cracker, traditional pikles, chiken satay', image: '' },
    // { id: 9, category_id: 2, name: 'Chicken Satay', description: 'grilled chicken skewers, peanut sauce, traditional pickles, steamed rice', image: '' },
    // { id: 10, category_id: 2, name: 'Sweet & Sour Chicken', description: 'fried chiken, sweet & sour sauce, capsicum, pineaple, onion', image: '' },
    // { id: 11, category_id: 2, name: 'Sweet & Sour Pork', description: 'pork, sweet & sour sauce, vegetables', image: '' },
    // { id: 12, category_id: 2, name: 'Butter Chicken', description: 'chicken, butter sauce, coriader, steamed white rice', image: '' },
    // { id: 13, category_id: 2, name: 'Chicken Teriyaki', description: 'chicken, teriyaki sauce, vegetables, steamed rice', image: '' },
    // { id: 14, category_id: 2, name: 'Capcay', description: 'mixed vegetables, oyster sauce, steamed rice', image: '' },
    // { id: 15, category_id: 2, name: 'Indosien Chicken Curry', description: 'chicken, rice indonesian curry sauce, steamed rice', image: '' },
    // { id: 16, category_id: 2, name: 'Thai Green Curry', description: 'spicy green curry, coconut cream, steamed rice', image: '' },
    // { id: 17, category_id: 2, name: 'Beef Bulgogi', description: 'marinated beef, steamed rice', image: '' },
    // { id: 18, category_id: 2, name: 'Traditional Chicken Parmigiana', descriptin: 'crumbed chicken breast, parmesan, melted cheese, steamed rice', image: '' },
    // { id: 19, category_id: 2, name: 'Chicken Schnitzel', description: 'crumbed chicken, parsley, lemon zest, steamed vegetables, mushroom sauce', image: '' },
    // { id: 20, category_id: 2, name: 'Chicken Cordon Bleu', description: 'crumbed chicken, ham, cheese, mashed potato, vegetables, mushroom sauce', image: '' },
    // { id: 21, category_id: 2, name: 'Chicken Grilled', description: 'marinated grilled chicken, rice, salad, sauce of choice', image: '' },
    // { id: 22, category_id: 2, name: 'Chicken Creamy Mushroom', description: 'chicken, mushrooms, creamy sauce, mashed potato', image: '' },
    // { id: 23, category_id: 2, name: 'Fish & Chips', description: 'Homemade battered fish, fries, Tartar sauce', image: '' },
    // { id: 24, category_id: 2, name: 'Crispy Skin Salmon', description: 'crispy salmon, sweet potato wedges, vegetable', image: '' },
    // { id: 25, category_id: 2, name: 'Creamy Garlic Prawn', description: 'prawns, creamy garlic sauce, steamed rice', image: '' },
    // { id: 26, category_id: 2, name: 'Beef Stroganoff', description: 'sliced beef, creamy mushroom sauce, steamed rice', image: '' },
    // { id: 27, category_id: 2, name: 'Mongolian Beef', description: 'classic beef, onions, spring onion, fried rice', image: '' },
    // { id: 28, category_id: 2, name: 'Chilli Con Carne', description: 'slow cooked minced beef, stewed beans, tomato sauce', image: '' },
    // // pizza & pasta
    // { id: 29, category_id: 4, name: 'Aglio Olio with Prawn/Chicken Grill', description: 'pasta, grilled prawn, grilled chicken, olive oil, chilli flakes, cherry tomato, parmesan, parsley', image: '' },
    // { id: 30, category_id: 4, name: 'Carbonara', description: 'pasta, bacon, mushroom, creamy sauce, parmesan', image: '' },
    // { id: 31, category_id: 4, name: 'Bolognese', description: 'pasta, minced beef, bolognese sauce, parmesan', image: '/images/bolognese.jpeg' },
    // { id: 32, category_id: 4, name: 'Seafood Spaghetti', description: 'spaghetti, prawns, calamari, paprika, parmesan', image: '' },
    // { id: 33, category_id: 4, name: 'Meat Lover Pizza', description: 'ham, salami, chicken, sausage, tomato sauce, cheddar, mozzarella', image: '' },
    // { id: 34, category_id: 4, name: 'Hawaiian Pizza', description: 'ham, pineapple, tomato sauce, cheddar, mozzarella', image: '' },
    // { id: 35, category_id: 4, name: 'Margareta Pizza', description: 'tomato sauce, Mozzarella, cheddar, Basil', image: '' },
    // { id: 36, category_id: 4, name: 'Seafood Pizza', description: 'calamari, prawns, onion, garlic, paprika, tomato sauce', image: '' },
    // { id: 37, category_id: 4, name: 'PIZZA GARLIC CHEESE', description: 'tortilla base, mozzarella chesse, garlic, cheddar, mozzarella', image: '' },
    // { id: 38, category_id: 4, name: 'GARLIC BREAD', description: 'toasted baguetta, garlic butter, parsley', image: '' },
    // { id: 39, category_id: 4, name: 'BRUSHETTA', description: 'toasted bread, tomato, olivr oil, basil', image: '' },
    // { id: 40, category_id: 4, name: 'MAC & CHEESE', description: 'macaroni, cheddar cheese, creamy cheese sauce', image: '' },
    // { id: 41, category_id: 4, name: 'MOZZARELLA STICKS', description: 'fried mozzarella sticks, marinara sauce', image: '' },
    // // Mocktails & Fresh Juices
    // { id: 42, category_id: 10, name: 'SHIRLEY TEMPLE', description: 'lemonade, lime juice, grenadine', image: '' },
    // { id: 43, category_id: 10, name: 'VIRGIN MOJITO', description: 'fresh mint, lime juice, soda water, sugar syrup', image: '' },
    // { id: 44, category_id: 10, name: 'PINA COLADA', description: 'pinapple jiuce, coconut cream, ice', image: '/images/DSC00206.jpg' },
    // { id: 45, category_id: 10, name: 'FRESH ORANGE JUICE', description: 'fresh orange juice', image: '' },
    // { id: 46, category_id: 10, name: 'FRESH MANGO JUICE', description: 'fresh mango juice', image: '/images/DSC00484.jpg' },

    // //Burgers & Sandwiches & Hot Dogs
    // { id: 47, category_id: 3, name: 'Triple Monkey', description: 'Beef Patty, Mushroom, Caramelized Onion, Fried Egg, Cheddar Cheese, Tomato, Lettuce, Ketchup, Mayo', image: '' },
    // { id: 48, category_id: 3, name: 'Cheese Burger', description: 'Beef Patty, Cheddar Cheese, Tomato, Lettuce, Ketchup, Mayo', image: '' },
    // { id: 49, category_id: 3, name: 'The Baconator', description: 'Beef Patty, Fried Egg, Bacon, Tomato, Lettuce, Cheddar Cheese, Ketchup, Mayo', image: '' },
    // { id: 50, category_id: 3, name: 'Supreme Beef Burger', description: 'Beef Patty, Lettuce, Tomato, Pickles, Cheddar Cheese', image: '' },
    // { id: 51, category_id: 3, name: 'The Ultimate Burger', description: 'Beef Patty, Cheddar Cheese, Caramelized Onion, Tomato, Lettuce, Ketchup, Mayo', image: '' },
    // { id: 52, category_id: 3, name: 'Chicken Burger', description: 'Crispy Fried Chicken, Lettuce, Tomato, Ketchup, Mayo', image: '' },
    // { id: 53, category_id: 3, name: "Uni's Club Sandwich", description: '3 Layer Toasted Sandwich, Grilled Chicken, Fresh Vegetables, Tomato, Cucumber, Lettuce, Mayo', image: '' },
    // { id: 54, category_id: 3, name: 'Juicy Steak BBQ Sauce', description: 'Tenderloin Beef Steak, BBQ Sauce, Bun, Fries', image: '' },
    // { id: 55, category_id: 3, name: 'BLT Sandwich', description: 'Bacon, Lettuce, Tomato, Toast, Fries', image: '' },
    // { id: 56, category_id: 3, name: 'The Classic Dog', description: 'Plain Hot Dog, Fresh Bun, Fried Onions, Tomato Sauce, Ketchup', image: '' },
    // { id: 57, category_id: 3, name: 'Cheese Dog', description: 'Hot Dog, Fresh Bun, Cheese, Fried Onions, Ketchup, Tomato Sauce', image: '' },
    // { id: 58, category_id: 3, name: 'Chilli Dog', description: 'Chopped Beef, Smoky Sauce, Fried Onion, Caramelized Onion', image: '' },
    // { id: 59, category_id: 3, name: 'Quesadilla', description: 'Tortilla, chicken, onion, capsicum, cheddar, mozzarella cheese', image: '' },
    // { id: 60, category_id: 3, name: "Taco's", description: 'Taco shell, ground beef, lettuce, cheddar, tomato, onion', image: '' },
    // { id: 61, category_id: 3, name: 'Nachos', description: 'Tortilla chips, jalapeños, guacamole, tomato, onion, Greek yogurt', image: '' },
    // { id: 62, category_id: 3, name: 'Chicken Tender', description: 'Fried chicken tenders, honey mustard, hot sauce', image: '' },
    // { id: 63, category_id: 3, name: 'Chicken Wrap', description: 'Grilled chicken, tortilla wrap, tomato, avocado, lettuce, mayonnaise', image: '' },
    // { id: 64, category_id: 3, name: 'Popcorn Chicken', description: 'Breaded chicken bites, sweet and sour sauce', image: '' },
    // { id: 65, category_id: 3, name: 'Onion Ring', description: 'Fried onion rings, ketchup', image: '' },
    // { id: 66, category_id: 3, name: "Chicken Wing's", description: 'Fried chicken wings, hot sauce', image: '' },
    // { id: 67, category_id: 3, name: 'Potato Wedges', description: 'Fried potato wedges, chili sauce', image: '' },
    // { id: 68, category_id: 3, name: 'Fries', description: 'French fries, salt', image: '' },
    // // Desserts & Cakes
    // { id: 69, category_id: 7, name: 'Cakes', description: 'Strawberry Tart, Tiramisu Cakes, Baked Cheese Cakes, Homemade Brownies, Banana Cakes', image: '' },
    // { id: 70, category_id: 7, name: 'Croissant', description: 'Butter Croissant, Almond Croissant', image: '' },
    // { id: 71, category_id: 7, name: 'Dessert', description: 'Banana or Pineapple Fritters, Ice Cream Ball', image: '' },
    // // Coffee & Tea
    // { id: 72, category_id: 8, name: 'Espresso single/double', description: 'Espresso shot', image: '' },
    // { id: 73, category_id: 8, name: 'Afagato', description: 'Espresso, Ice cream', image: '' },
    // { id: 74, category_id: 8, name: 'Long black', description: 'Hot water, Espresso', image: '' },
    // { id: 75, category_id: 8, name: 'Piccolo latte', description: 'Espresso, Steamed milk', image: '' },
    // { id: 76, category_id: 8, name: 'Flat white (hot/ice)', description: 'Espresso, Steamed milk, Foam', image: '' },
    // { id: 77, category_id: 8, name: 'Cappuccino (hot/ice)', description: 'Espresso, Steamed milk, Foam', image: '' },
    // { id: 78, category_id: 8, name: 'Latte (hot/ice)', description: 'Espresso, Steamed milk', image: '' },
    // { id: 79, category_id: 8, name: 'Macchiato (hot)', description: 'Espresso, Foam', image: '' },
    // { id: 80, category_id: 8, name: 'Iced coffee', description: 'Espresso, Ice, Milk', image: '' },
    // { id: 81, category_id: 8, name: 'Matcha (hot/ice)', description: 'Matcha powder, Milk', image: '' },
    // { id: 82, category_id: 8, name: 'Mocha (hot/ice)', description: 'Espresso, Chocolate, Milk', image: '' },
    // { id: 83, category_id: 8, name: 'Avocado coffee (ice)', description: 'Espresso, Avocado, Ice', image: '' },
    // { id: 84, category_id: 8, name: 'Coffee palm sugar (ice)', description: 'Espresso, Palm sugar, Ice', image: '' },
    // { id: 85, category_id: 8, name: 'CHOCOLATE (hot/ice)', description: 'Chocolate, Milk', image: '' },
    // { id: 86, category_id: 8, name: 'EXTRA', description: 'Extra shot espresso, Soy Milk, Caramel, Hazelnut, Vanilla, Almond milk, Coconut milk, Oat milk', image: '' },
    // { id: 87, category_id: 8, name: 'Lipton (pot)', description: 'Lipton tea', image: '' },
    // { id: 88, category_id: 8, name: 'English breakfast (pot)', description: 'Black tea', image: '' },
    // { id: 89, category_id: 8, name: 'Green tea (hot/ice)', description: 'Green tea', image: '' },
    // { id: 90, category_id: 8, name: 'Lemon tea (hot/ice)', description: 'Lemon, Tea', image: '' },
    // { id: 91, category_id: 8, name: 'Lemon grass tea (hot/ice)', description: 'Lemongrass, Tea', image: '' },
    // { id: 92, category_id: 8, name: 'Chamomille tea (hot/ice)', description: 'Chamomile, Tea', image: '' },
    // { id: 93, category_id: 8, name: 'Earl grey', description: 'Black tea, Bergamot', image: '' },
    // { id: 94, category_id: 8, name: 'Jasmine tea (hot/ice)', description: 'Jasmine, Tea', image: '' },
    // { id: 95, category_id: 8, name: 'Ginger tea (hot)', description: 'Ginger, Tea', image: '' },
    // { id: 96, category_id: 8, name: 'MILKSHAKE', description: 'Chocolate, Strawberry, Milo, Banana', image: '' },
    // { id: 97, category_id: 8, name: 'FRAPPE', description: 'Caramel, Chai, Hazelnut, Vanilla', image: '' },
    // { id: 98, category_id: 8, name: 'SMOOTHIE FRUIT & YOGURT', description: 'Banana, Strawberry, Mango, Red dragon fruit, Yogurt', image: '' },
    // { id: 99, category_id: 8, name: 'COCOA SMOOTHIE', description: 'Mango, Banana, Blueberry, Cocoa, Dates, Almond milk, Coconut water, Cocoa nibs', image: '' },
    // //Beverages
    // { id: 100, category_id: 9, name: 'Virgin Mojito', description: 'Mint, Lime, Soda, Sugar', image: '' },
    // { id: 101, category_id: 9, name: 'BEER', description: 'Lager Beer, Pale Ale', image: '' },
    // { id: 102, category_id: 9, name: 'CIDER', description: 'Apple Cider, Pear Cider', image: '' },
    // { id: 103, category_id: 9, name: 'GIN & TONIC', description: 'Gin, Tonic Water, Lime', image: '' },
    // { id: 104, category_id: 9, name: 'WHISKEY & COLA', description: 'Whiskey, Coke, Ice', image: '' },
    // { id: 105, category_id: 9, name: 'RED WINE GLASS', description: 'Red Wine', image: '' },
    // { id: 106, category_id: 9, name: 'WHITE WINE GLASS', description: 'White Wine', image: '' },
    // { id: 107, category_id: 9, name: 'SPARKLING WATER', description: 'Carbonated Water', image: '' },
    // { id: 108, category_id: 9, name: 'COLA', description: 'Cola Soda', image: '' },
    // { id: 109, category_id: 9, name: 'GINGER ALE', description: 'Ginger Ale', image: '' },
    // { id: 110, category_id: 9, name: 'TONIC WATER', description: 'Tonic Water', image: '' },
    // { id: 111, category_id: 9, name: 'MINERAL WATER SMALL', description: 'Mineral Water 0.5L', image: '' },
    // { id: 112, category_id: 9, name: 'MINERAL WATER LARGE', description: 'Mineral Water 1.5L', image: '' },
    // { id: 113, category_id: 9, name: 'RED BULL', description: 'Energy Drink', image: '' },
    // { id: 114, category_id: 9, name: 'ICED TEA', description: 'Brewed Tea, Lemon, Ice', image: '' },
    // { id: 115, category_id: 9, name: 'Strawberry Lemonade', description: 'Strawberries, Lemon Juice, Soda', image: '' },
    // { id: 116, category_id: 9, name: 'Mango Cooler', description: 'Mango Puree, Soda, Mint', image: '' },
    // { id: 117, category_id: 9, name: 'Fresh Orange Juice', description: 'Fresh Oranges', image: '' },
    // { id: 118, category_id: 9, name: 'Fresh Watermelon Juice', description: 'Fresh Watermelon', image: '' },
    // { id: 119, category_id: 9, name: 'Cucumber Cooler', description: 'Cucumber, Mint, Lime, Soda', image: '' },
    // { id: 120, category_id: 9, name: 'Pineapple Fizz', description: 'Pineapple Juice, Soda, Lime', image: '' },
    // { id: 121, category_id: 9, name: 'Citrus Cooler', description: 'Lemon, Orange, Soda, Mint', image: '' },
    // // Cocktails & Spirits
    // { id: 122, category_id: 11, name: 'MOJITO CLASSIC', description: 'White Rum, Mint, Lime Juice, Sugar Syrup, Soda Water', image: '' },
    // { id: 123, category_id: 11, name: 'COSMOPOLITAN', description: 'Vodka, Triple Sec, Cranberry Juice, Lime Juice', image: '' },
    // { id: 124, category_id: 11, name: 'MARGARITA', description: 'Tequila, Triple Sec, Lime Juice, Salt Rim', image: '' },
    // { id: 125, category_id: 11, name: 'MOJITO STRAWBERRY', description: 'White Rum, Mint, Strawberry Syrup, Lime Juice, Soda Water', image: '' },
    // { id: 126, category_id: 11, name: 'SEX ON THE BEACH', description: 'Vodka, Peach Schnapps, Orange Juice, Cranberry Juice', image: '' },
    // // Shooters
    // { id: 127, category_id: 12, name: 'B52', description: 'Kahlua, Baileys, Grand Marnier', image: '' },
    // { id: 128, category_id: 12, name: 'KAMIKAZE', description: 'Vodka, Triple Sec, Lime Juice', image: '' },
    // { id: 129, category_id: 12, name: 'TEQUILA SHOT', description: 'Tequila, Salt, Lime', image: '' }
    { id: 130, image: '/images/bolognese.jpeg', name: 'spaghetti bolognese'},
    { id: 131, image: '/images/Braised_pork_belly.jpeg', name: 'Braised Pork belly'},
    { id: 132, image: '/images/caesar_salad.jpeg', name: 'Caesar Salad'},
    { id: 133, image: '/images/chiken_cashewnuts.jpeg', name: 'Chiken Cashewnuts'},
    { id: 134, image: '/images/chiken_strip_with_vegetable.jpeg', name: 'Chiken Strip With Vegetables'},
    { id: 135, image: '/images/Chirashi_sushi.jpeg', name: 'Chirashi Sushi'},
    { id: 136, image: '/images/crispy_tuna_poke.jpeg', name: 'Crispy Tuna Poke'},
    { id: 137, image: '/images/cucumber_crab_salad.jpeg', name: 'Cucumber Crab Salad'},
    { id: 138, image: '/images/Egg_drop_soup.jpeg', name: 'Egg Drop Soup'},
    { id: 139, image: '/images/Flying_crawfish roll.jpeg', name: 'Flying Crawfish Roll'},
    { id: 140, image: '/images/golden_roll.jpeg', name: 'Golden Roll'},
    { id: 141, image: '/images/nachos.jpeg', name: 'Nachos'},
    { id: 142, image: 'images/pan_fried_gyoza.jpeg', name: 'Pan Fried Gyoza'},
    { id: 143, image: '/images/pizza.jpeg', name: 'Pizza'},
    { id: 144, image: '/images/pork_coy.jpeg', name: 'Pork Coy'},
    { id: 145, image: '/images/royal_roll.jpeg', name: 'Royal roll'},
    { id: 146, image: '/images/sake_kama_grilled salmon_collar.jpeg', name: 'Grilled Salmon Collar'},
    { id: 147, image: '/images/sashimi.jpeg', name: 'Sashimi'},
    { id: 148, image: '/images/seared_tuna.jpeg', name: 'Seared Tuna'},
    { id: 149, image: '/images/sizzling_steak.jpeg', name: 'Sizzling Steak'},
    { id: 150, image: '/images/sushi_taco.jpeg', name: 'Sushi Taco'},
    { id: 151, image: '/images/sushi.jpeg', name: 'Sushi'},
    { id: 152, image: '/images/tom_yum_soup.jpeg', name: 'Tom Yum Soup'},
    { id: 153, image: '/images/tuna_tataki.jpeg', name: 'Tuna Tataki'},
    { id: 154, image: '/images/volcano_roll.jpeg', name: 'Volcano Roll'},  
  ],
  // gallery: [
  //   { id: 1, image: '/images/IMG_3696.jpg',},
  //   { id: 2, image: '/images/IMG_6304.jpg'},
  //   { id: 3, image: '/images/IMG_6306.jpg'},
  //   { id: 4, image: '/images/IMG_6328.jpg'},
  //   { id: 5, image: '/images/IMG_6462.jpg'},
  //   { id: 6, image: '/images/IMG_6539.jpg'},
  //   { id: 7, image: '/images/IMG_6710.jpg'},
  //   { id: 8, image: '/images/IMG_6711.jpg'},
  //   { id: 9, image: '/images/IMG_6712.jpg'}
  // ],

  katalog: [
  ],
};